import { Player } from '../models/player.model';
import { SkaterPosition } from '../models/position.model';

// Curated, static sample dataset for the public landing-page demo. Approximate
// 2024-25-style projections for a spread of well-known players across positions
// and teams - enough to make the live re-ranking feel real without any backend
// call (the real /players endpoints require auth). Not synced; illustrative only.
export const DEMO_PLAYERS: Player[] = [
  {
    id: 1,
    type: 'skater',
    name: 'Connor McDavid',
    teamAbbrev: 'EDM',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/EDM/8478402.png',
    positions: new Set<SkaterPosition>(['C']),
    stats: {
      utility: { gp: 76, toiPerGame: 1314 },
      scoring: {
        goals: 32,
        assists: 68,
        points: 100,
        plusMinus: 20,
        pim: 26,
        ppg: 13,
        ppa: 29,
        ppp: 42,
        shg: 0,
        sha: 0,
        shp: 0,
        gwg: 5,
        sog: 211,
        shPct: 15.2,
        fw: 663,
        fl: 705,
        hits: 49,
        blocks: 31,
      },
    },
  },
  {
    id: 2,
    type: 'skater',
    name: 'Nathan MacKinnon',
    teamAbbrev: 'COL',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/COL/8477492.png',
    positions: new Set<SkaterPosition>(['C']),
    stats: {
      utility: { gp: 82, toiPerGame: 1326 },
      scoring: {
        goals: 51,
        assists: 89,
        points: 140,
        plusMinus: 22,
        pim: 42,
        ppg: 20,
        ppa: 37,
        ppp: 57,
        shg: 2,
        sha: 0,
        shp: 2,
        gwg: 8,
        sog: 317,
        shPct: 16.1,
        fw: 658,
        fl: 818,
        hits: 71,
        blocks: 47,
      },
    },
  },
  {
    id: 3,
    type: 'skater',
    name: 'Leon Draisaitl',
    teamAbbrev: 'EDM',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/EDM/8477934.png',
    positions: new Set<SkaterPosition>(['C', 'LW']),
    stats: {
      utility: { gp: 80, toiPerGame: 1260 },
      scoring: {
        goals: 52,
        assists: 54,
        points: 106,
        plusMinus: 31,
        pim: 40,
        ppg: 21,
        ppa: 23,
        ppp: 44,
        shg: 0,
        sha: 0,
        shp: 0,
        gwg: 8,
        sog: 275,
        shPct: 18.9,
        fw: 765,
        fl: 675,
        hits: 52,
        blocks: 26,
      },
    },
  },
  {
    id: 4,
    type: 'skater',
    name: 'Nikita Kucherov',
    teamAbbrev: 'TBL',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/TBL/8476453.png',
    positions: new Set<SkaterPosition>(['RW']),
    stats: {
      utility: { gp: 80, toiPerGame: 1254 },
      scoring: {
        goals: 37,
        assists: 84,
        points: 121,
        plusMinus: 24,
        pim: 30,
        ppg: 15,
        ppa: 35,
        ppp: 50,
        shg: 1,
        sha: 1,
        shp: 2,
        gwg: 6,
        sog: 268,
        shPct: 13.8,
        fw: 33,
        fl: 42,
        hits: 29,
        blocks: 37,
      },
    },
  },
  {
    id: 5,
    type: 'skater',
    name: 'David Pastrnak',
    teamAbbrev: 'BOS',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/BOS/8477956.png',
    positions: new Set<SkaterPosition>(['RW']),
    stats: {
      utility: { gp: 82, toiPerGame: 1188 },
      scoring: {
        goals: 43,
        assists: 63,
        points: 106,
        plusMinus: -2,
        pim: 44,
        ppg: 17,
        ppa: 26,
        ppp: 43,
        shg: 1,
        sha: 0,
        shp: 1,
        gwg: 7,
        sog: 289,
        shPct: 14.9,
        fw: 36,
        fl: 60,
        hits: 64,
        blocks: 35,
      },
    },
  },
  {
    id: 6,
    type: 'skater',
    name: 'Kirill Kaprizov',
    teamAbbrev: 'MIN',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/MIN/8478864.png',
    positions: new Set<SkaterPosition>(['LW']),
    stats: {
      utility: { gp: 41, toiPerGame: 1278 },
      scoring: {
        goals: 25,
        assists: 31,
        points: 56,
        plusMinus: 10,
        pim: 22,
        ppg: 10,
        ppa: 13,
        ppp: 23,
        shg: 0,
        sha: 0,
        shp: 0,
        gwg: 4,
        sog: 140,
        shPct: 17.9,
        fw: 44,
        fl: 33,
        hits: 58,
        blocks: 20,
      },
    },
  },
  {
    id: 7,
    type: 'skater',
    name: 'Auston Matthews',
    teamAbbrev: 'TOR',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/TOR/8479318.png',
    positions: new Set<SkaterPosition>(['C']),
    stats: {
      utility: { gp: 67, toiPerGame: 1284 },
      scoring: {
        goals: 33,
        assists: 45,
        points: 78,
        plusMinus: 21,
        pim: 48,
        ppg: 13,
        ppa: 19,
        ppp: 32,
        shg: 1,
        sha: 0,
        shp: 1,
        gwg: 5,
        sog: 241,
        shPct: 13.7,
        fw: 631,
        fl: 575,
        hits: 73,
        blocks: 55,
      },
    },
  },
  {
    id: 8,
    type: 'skater',
    name: 'Mikko Rantanen',
    teamAbbrev: 'DAL',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/DAL/8478420.png',
    positions: new Set<SkaterPosition>(['RW']),
    stats: {
      utility: { gp: 78, toiPerGame: 1236 },
      scoring: {
        goals: 38,
        assists: 50,
        points: 88,
        plusMinus: 18,
        pim: 40,
        ppg: 15,
        ppa: 21,
        ppp: 36,
        shg: 0,
        sha: 0,
        shp: 0,
        gwg: 6,
        sog: 259,
        shPct: 14.7,
        fw: 20,
        fl: 29,
        hits: 78,
        blocks: 41,
      },
    },
  },
  {
    id: 9,
    type: 'skater',
    name: 'Jack Hughes',
    teamAbbrev: 'NJD',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/NJD/8481559.png',
    positions: new Set<SkaterPosition>(['C']),
    stats: {
      utility: { gp: 62, toiPerGame: 1224 },
      scoring: {
        goals: 27,
        assists: 43,
        points: 70,
        plusMinus: 7,
        pim: 20,
        ppg: 11,
        ppa: 18,
        ppp: 29,
        shg: 1,
        sha: 1,
        shp: 2,
        gwg: 4,
        sog: 206,
        shPct: 13.1,
        fw: 527,
        fl: 589,
        hits: 41,
        blocks: 26,
      },
    },
  },
  {
    id: 10,
    type: 'skater',
    name: 'Matthew Tkachuk',
    teamAbbrev: 'FLA',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/FLA/8479314.png',
    positions: new Set<SkaterPosition>(['LW']),
    stats: {
      utility: { gp: 52, toiPerGame: 1194 },
      scoring: {
        goals: 22,
        assists: 35,
        points: 57,
        plusMinus: 15,
        pim: 84,
        ppg: 9,
        ppa: 15,
        ppp: 24,
        shg: 0,
        sha: 0,
        shp: 0,
        gwg: 4,
        sog: 172,
        shPct: 12.8,
        fw: 74,
        fl: 43,
        hits: 120,
        blocks: 33,
      },
    },
  },
  {
    id: 11,
    type: 'skater',
    name: 'Brady Tkachuk',
    teamAbbrev: 'OTT',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/OTT/8480801.png',
    positions: new Set<SkaterPosition>(['LW']),
    stats: {
      utility: { gp: 72, toiPerGame: 1152 },
      scoring: {
        goals: 29,
        assists: 26,
        points: 55,
        plusMinus: -3,
        pim: 92,
        ppg: 12,
        ppa: 11,
        ppp: 23,
        shg: 2,
        sha: 1,
        shp: 3,
        gwg: 5,
        sog: 215,
        shPct: 13.5,
        fw: 61,
        fl: 45,
        hits: 244,
        blocks: 49,
      },
    },
  },
  {
    id: 12,
    type: 'skater',
    name: 'Sidney Crosby',
    teamAbbrev: 'PIT',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/PIT/8471675.png',
    positions: new Set<SkaterPosition>(['C']),
    stats: {
      utility: { gp: 80, toiPerGame: 1206 },
      scoring: {
        goals: 33,
        assists: 58,
        points: 91,
        plusMinus: -19,
        pim: 32,
        ppg: 13,
        ppa: 24,
        ppp: 37,
        shg: 2,
        sha: 1,
        shp: 3,
        gwg: 5,
        sog: 223,
        shPct: 14.8,
        fw: 779,
        fl: 661,
        hits: 66,
        blocks: 44,
      },
    },
  },
  {
    id: 13,
    type: 'skater',
    name: 'Artemi Panarin',
    teamAbbrev: 'NYR',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/NYR/8478550.png',
    positions: new Set<SkaterPosition>(['LW']),
    stats: {
      utility: { gp: 80, toiPerGame: 1182 },
      scoring: {
        goals: 37,
        assists: 52,
        points: 89,
        plusMinus: -4,
        pim: 18,
        ppg: 15,
        ppa: 22,
        ppp: 37,
        shg: 1,
        sha: 0,
        shp: 1,
        gwg: 6,
        sog: 262,
        shPct: 14.1,
        fw: 30,
        fl: 49,
        hits: 44,
        blocks: 29,
      },
    },
  },
  {
    id: 14,
    type: 'skater',
    name: 'Mitch Marner',
    teamAbbrev: 'TOR',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/TOR/8478483.png',
    positions: new Set<SkaterPosition>(['RW']),
    stats: {
      utility: { gp: 81, toiPerGame: 1266 },
      scoring: {
        goals: 27,
        assists: 75,
        points: 102,
        plusMinus: 25,
        pim: 22,
        ppg: 11,
        ppa: 32,
        ppp: 43,
        shg: 0,
        sha: 1,
        shp: 1,
        gwg: 4,
        sog: 208,
        shPct: 13,
        fw: 23,
        fl: 37,
        hits: 38,
        blocks: 53,
      },
    },
  },
  {
    id: 15,
    type: 'skater',
    name: 'William Nylander',
    teamAbbrev: 'TOR',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/TOR/8477939.png',
    positions: new Set<SkaterPosition>(['RW', 'C']),
    stats: {
      utility: { gp: 82, toiPerGame: 1188 },
      scoring: {
        goals: 45,
        assists: 39,
        points: 84,
        plusMinus: 8,
        pim: 26,
        ppg: 18,
        ppa: 16,
        ppp: 34,
        shg: 2,
        sha: 1,
        shp: 3,
        gwg: 7,
        sog: 274,
        shPct: 16.4,
        fw: 765,
        fl: 711,
        hits: 49,
        blocks: 35,
      },
    },
  },
  {
    id: 16,
    type: 'skater',
    name: 'Jason Robertson',
    teamAbbrev: 'DAL',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/DAL/8480027.png',
    positions: new Set<SkaterPosition>(['LW']),
    stats: {
      utility: { gp: 82, toiPerGame: 1140 },
      scoring: {
        goals: 35,
        assists: 45,
        points: 80,
        plusMinus: 12,
        pim: 34,
        ppg: 14,
        ppa: 19,
        ppp: 33,
        shg: 2,
        sha: 1,
        shp: 3,
        gwg: 6,
        sog: 255,
        shPct: 13.7,
        fw: 67,
        fl: 41,
        hits: 66,
        blocks: 42,
      },
    },
  },
  {
    id: 17,
    type: 'skater',
    name: 'Aleksander Barkov',
    teamAbbrev: 'FLA',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/FLA/8477493.png',
    positions: new Set<SkaterPosition>(['C']),
    stats: {
      utility: { gp: 67, toiPerGame: 1272 },
      scoring: {
        goals: 20,
        assists: 51,
        points: 71,
        plusMinus: 32,
        pim: 28,
        ppg: 8,
        ppa: 21,
        ppp: 29,
        shg: 0,
        sha: 1,
        shp: 1,
        gwg: 3,
        sog: 192,
        shPct: 10.4,
        fw: 707,
        fl: 499,
        hits: 53,
        blocks: 54,
      },
    },
  },
  {
    id: 18,
    type: 'skater',
    name: 'Sam Reinhart',
    teamAbbrev: 'FLA',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/FLA/8477933.png',
    positions: new Set<SkaterPosition>(['C', 'RW']),
    stats: {
      utility: { gp: 79, toiPerGame: 1134 },
      scoring: {
        goals: 39,
        assists: 42,
        points: 81,
        plusMinus: 20,
        pim: 24,
        ppg: 16,
        ppa: 18,
        ppp: 34,
        shg: 2,
        sha: 1,
        shp: 3,
        gwg: 6,
        sog: 220,
        shPct: 17.7,
        fw: 728,
        fl: 694,
        hits: 47,
        blocks: 38,
      },
    },
  },
  {
    id: 19,
    type: 'skater',
    name: 'Cale Makar',
    teamAbbrev: 'COL',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/COL/8480069.png',
    positions: new Set<SkaterPosition>(['D']),
    stats: {
      utility: { gp: 80, toiPerGame: 1524 },
      scoring: {
        goals: 28,
        assists: 64,
        points: 92,
        plusMinus: 25,
        pim: 30,
        ppg: 14,
        ppa: 27,
        ppp: 41,
        shg: 2,
        sha: 1,
        shp: 3,
        gwg: 4,
        sog: 231,
        shPct: 12.1,
        fw: 6,
        fl: 12,
        hits: 84,
        blocks: 131,
      },
    },
  },
  {
    id: 20,
    type: 'skater',
    name: 'Quinn Hughes',
    teamAbbrev: 'VAN',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/VAN/8480800.png',
    positions: new Set<SkaterPosition>(['D']),
    stats: {
      utility: { gp: 68, toiPerGame: 1512 },
      scoring: {
        goals: 16,
        assists: 60,
        points: 76,
        plusMinus: 26,
        pim: 20,
        ppg: 8,
        ppa: 25,
        ppp: 33,
        shg: 1,
        sha: 0,
        shp: 1,
        gwg: 3,
        sog: 203,
        shPct: 7.9,
        fw: 1,
        fl: 3,
        hits: 42,
        blocks: 96,
      },
    },
  },
  {
    id: 21,
    type: 'skater',
    name: 'Roman Josi',
    teamAbbrev: 'NSH',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/NSH/8474600.png',
    positions: new Set<SkaterPosition>(['D']),
    stats: {
      utility: { gp: 82, toiPerGame: 1530 },
      scoring: {
        goals: 14,
        assists: 55,
        points: 69,
        plusMinus: -4,
        pim: 34,
        ppg: 7,
        ppa: 23,
        ppp: 30,
        shg: 2,
        sha: 0,
        shp: 2,
        gwg: 2,
        sog: 182,
        shPct: 7.7,
        fw: 1,
        fl: 3,
        hits: 96,
        blocks: 152,
      },
    },
  },
  {
    id: 22,
    type: 'skater',
    name: 'Victor Hedman',
    teamAbbrev: 'TBL',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/TBL/8475167.png',
    positions: new Set<SkaterPosition>(['D']),
    stats: {
      utility: { gp: 78, toiPerGame: 1446 },
      scoring: {
        goals: 15,
        assists: 52,
        points: 67,
        plusMinus: 20,
        pim: 44,
        ppg: 8,
        ppa: 22,
        ppp: 30,
        shg: 2,
        sha: 1,
        shp: 3,
        gwg: 2,
        sog: 183,
        shPct: 8.2,
        fw: 8,
        fl: 10,
        hits: 112,
        blocks: 148,
      },
    },
  },
  {
    id: 23,
    type: 'skater',
    name: 'Adam Fox',
    teamAbbrev: 'NYR',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/NYR/8479323.png',
    positions: new Set<SkaterPosition>(['D']),
    stats: {
      utility: { gp: 73, toiPerGame: 1458 },
      scoring: {
        goals: 13,
        assists: 49,
        points: 62,
        plusMinus: 18,
        pim: 20,
        ppg: 7,
        ppa: 21,
        ppp: 28,
        shg: 0,
        sha: 1,
        shp: 1,
        gwg: 2,
        sog: 140,
        shPct: 9.3,
        fw: 4,
        fl: 6,
        hits: 58,
        blocks: 124,
      },
    },
  },
  {
    id: 24,
    type: 'skater',
    name: 'Zach Werenski',
    teamAbbrev: 'CBJ',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/CBJ/8478460.png',
    positions: new Set<SkaterPosition>(['D']),
    stats: {
      utility: { gp: 81, toiPerGame: 1596 },
      scoring: {
        goals: 23,
        assists: 59,
        points: 82,
        plusMinus: 7,
        pim: 40,
        ppg: 12,
        ppa: 25,
        ppp: 37,
        shg: 1,
        sha: 0,
        shp: 1,
        gwg: 4,
        sog: 242,
        shPct: 9.5,
        fw: 5,
        fl: 3,
        hits: 101,
        blocks: 167,
      },
    },
  },
  {
    id: 25,
    type: 'skater',
    name: 'Jesper Bratt',
    teamAbbrev: 'NJD',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/NJD/8479407.png',
    positions: new Set<SkaterPosition>(['LW']),
    stats: {
      utility: { gp: 81, toiPerGame: 1176 },
      scoring: {
        goals: 21,
        assists: 67,
        points: 88,
        plusMinus: 15,
        pim: 22,
        ppg: 8,
        ppa: 28,
        ppp: 36,
        shg: 0,
        sha: 1,
        shp: 1,
        gwg: 3,
        sog: 181,
        shPct: 11.6,
        fw: 47,
        fl: 26,
        hits: 51,
        blocks: 34,
      },
    },
  },
  {
    id: 26,
    type: 'skater',
    name: 'Kyle Connor',
    teamAbbrev: 'WPG',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/WPG/8478398.png',
    positions: new Set<SkaterPosition>(['LW']),
    stats: {
      utility: { gp: 82, toiPerGame: 1164 },
      scoring: {
        goals: 41,
        assists: 56,
        points: 97,
        plusMinus: 17,
        pim: 20,
        ppg: 16,
        ppa: 24,
        ppp: 40,
        shg: 2,
        sha: 0,
        shp: 2,
        gwg: 7,
        sog: 259,
        shPct: 15.8,
        fw: 58,
        fl: 62,
        hits: 45,
        blocks: 31,
      },
    },
  },
  {
    id: 27,
    type: 'skater',
    name: 'Tage Thompson',
    teamAbbrev: 'BUF',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/BUF/8479420.png',
    positions: new Set<SkaterPosition>(['C']),
    stats: {
      utility: { gp: 76, toiPerGame: 1146 },
      scoring: {
        goals: 44,
        assists: 28,
        points: 72,
        plusMinus: -2,
        pim: 58,
        ppg: 18,
        ppa: 12,
        ppp: 30,
        shg: 1,
        sha: 0,
        shp: 1,
        gwg: 7,
        sog: 259,
        shPct: 17,
        fw: 691,
        fl: 677,
        hits: 141,
        blocks: 44,
      },
    },
  },
  {
    id: 28,
    type: 'skater',
    name: 'Elias Pettersson',
    teamAbbrev: 'VAN',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/VAN/8480012.png',
    positions: new Set<SkaterPosition>(['C']),
    stats: {
      utility: { gp: 82, toiPerGame: 1200 },
      scoring: {
        goals: 15,
        assists: 30,
        points: 45,
        plusMinus: -11,
        pim: 34,
        ppg: 6,
        ppa: 13,
        ppp: 19,
        shg: 2,
        sha: 0,
        shp: 2,
        gwg: 2,
        sog: 160,
        shPct: 9.4,
        fw: 772,
        fl: 704,
        hits: 68,
        blocks: 49,
      },
    },
  },
  {
    id: 29,
    type: 'skater',
    name: 'Macklin Celebrini',
    teamAbbrev: 'SJS',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/SJS/8484801.png',
    positions: new Set<SkaterPosition>(['C']),
    stats: {
      utility: { gp: 70, toiPerGame: 1170 },
      scoring: {
        goals: 25,
        assists: 38,
        points: 63,
        plusMinus: -18,
        pim: 30,
        ppg: 10,
        ppa: 16,
        ppp: 26,
        shg: 0,
        sha: 1,
        shp: 1,
        gwg: 4,
        sog: 189,
        shPct: 13.2,
        fw: 602,
        fl: 658,
        hits: 63,
        blocks: 53,
      },
    },
  },
  {
    id: 30,
    type: 'skater',
    name: 'Connor Bedard',
    teamAbbrev: 'CHI',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/CHI/8484144.png',
    positions: new Set<SkaterPosition>(['C']),
    stats: {
      utility: { gp: 68, toiPerGame: 1212 },
      scoring: {
        goals: 23,
        assists: 44,
        points: 67,
        plusMinus: -24,
        pim: 26,
        ppg: 9,
        ppa: 18,
        ppp: 27,
        shg: 0,
        sha: 0,
        shp: 0,
        gwg: 4,
        sog: 193,
        shPct: 11.9,
        fw: 546,
        fl: 678,
        hits: 49,
        blocks: 31,
      },
    },
  },
  {
    id: 31,
    type: 'skater',
    name: 'Robert Thomas',
    teamAbbrev: 'STL',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/STL/8480023.png',
    positions: new Set<SkaterPosition>(['C']),
    stats: {
      utility: { gp: 70, toiPerGame: 1218 },
      scoring: {
        goals: 21,
        assists: 60,
        points: 81,
        plusMinus: 9,
        pim: 18,
        ppg: 8,
        ppa: 25,
        ppp: 33,
        shg: 1,
        sha: 1,
        shp: 2,
        gwg: 3,
        sog: 179,
        shPct: 11.7,
        fw: 658,
        fl: 602,
        hits: 45,
        blocks: 41,
      },
    },
  },
  {
    id: 32,
    type: 'skater',
    name: 'Filip Forsberg',
    teamAbbrev: 'NSH',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/NSH/8476887.png',
    positions: new Set<SkaterPosition>(['LW', 'RW']),
    stats: {
      utility: { gp: 82, toiPerGame: 1158 },
      scoring: {
        goals: 33,
        assists: 43,
        points: 76,
        plusMinus: 3,
        pim: 38,
        ppg: 13,
        ppa: 18,
        ppp: 31,
        shg: 0,
        sha: 1,
        shp: 1,
        gwg: 5,
        sog: 232,
        shPct: 14.2,
        fw: 47,
        fl: 36,
        hits: 88,
        blocks: 45,
      },
    },
  },
  {
    id: 33,
    type: 'goalie',
    name: 'Connor Hellebuyck',
    teamAbbrev: 'WPG',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/WPG/8476945.png',
    stats: {
      utility: { gp: 63 },
      scoring: { gs: 63, w: 47, l: 12, sho: 8, sa: 1627, sv: 1505, ga: 122, gaa: 2, svPct: 0.925 },
    },
  },
  {
    id: 34,
    type: 'goalie',
    name: 'Igor Shesterkin',
    teamAbbrev: 'NYR',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/NYR/8478048.png',
    stats: {
      utility: { gp: 58 },
      scoring: {
        gs: 58,
        w: 27,
        l: 24,
        sho: 3,
        sa: 1684,
        sv: 1524,
        ga: 160,
        gaa: 2.86,
        svPct: 0.905,
      },
    },
  },
  {
    id: 35,
    type: 'goalie',
    name: 'Andrei Vasilevskiy',
    teamAbbrev: 'TBL',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/TBL/8476883.png',
    stats: {
      utility: { gp: 63 },
      scoring: {
        gs: 63,
        w: 38,
        l: 20,
        sho: 5,
        sa: 1684,
        sv: 1551,
        ga: 133,
        gaa: 2.18,
        svPct: 0.921,
      },
    },
  },
  {
    id: 36,
    type: 'goalie',
    name: 'Juuse Saros',
    teamAbbrev: 'NSH',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/NSH/8477424.png',
    stats: {
      utility: { gp: 63 },
      scoring: {
        gs: 63,
        w: 26,
        l: 30,
        sho: 3,
        sa: 1755,
        sv: 1590,
        ga: 165,
        gaa: 2.71,
        svPct: 0.906,
      },
    },
  },
  {
    id: 37,
    type: 'goalie',
    name: 'Jake Oettinger',
    teamAbbrev: 'DAL',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/DAL/8479979.png',
    stats: {
      utility: { gp: 58 },
      scoring: {
        gs: 58,
        w: 36,
        l: 17,
        sho: 3,
        sa: 1560,
        sv: 1418,
        ga: 142,
        gaa: 2.53,
        svPct: 0.909,
      },
    },
  },
  {
    id: 38,
    type: 'goalie',
    name: 'Ilya Sorokin',
    teamAbbrev: 'NYI',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/NYI/8478009.png',
    stats: {
      utility: { gp: 55 },
      scoring: {
        gs: 55,
        w: 25,
        l: 22,
        sho: 3,
        sa: 1570,
        sv: 1424,
        ga: 146,
        gaa: 2.75,
        svPct: 0.907,
      },
    },
  },
  {
    id: 39,
    type: 'goalie',
    name: 'Jeremy Swayman',
    teamAbbrev: 'BOS',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/BOS/8480280.png',
    stats: {
      utility: { gp: 58 },
      scoring: {
        gs: 58,
        w: 22,
        l: 29,
        sho: 2,
        sa: 1611,
        sv: 1437,
        ga: 174,
        gaa: 3.11,
        svPct: 0.892,
      },
    },
  },
  {
    id: 40,
    type: 'goalie',
    name: 'Filip Gustavsson',
    teamAbbrev: 'MIN',
    headshot: 'https://assets.nhle.com/mugs/nhl/20242025/MIN/8479406.png',
    stats: {
      utility: { gp: 58 },
      scoring: {
        gs: 58,
        w: 31,
        l: 21,
        sho: 4,
        sa: 1674,
        sv: 1530,
        ga: 144,
        gaa: 2.56,
        svPct: 0.914,
      },
    },
  },
];
