/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SkaterResponse } from '../../models/skater-response';

export interface GetSkaters$Params {}

export function getSkaters(
  http: HttpClient,
  rootUrl: string,
  params?: GetSkaters$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<SkaterResponse>>> {
  const rb = new RequestBuilder(rootUrl, getSkaters.PATH, 'get');
  if (params) {
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SkaterResponse>>;
    }),
  );
}

getSkaters.PATH = '/api/v1/players/skaters';
