/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GoalieResponse } from '../../models/goalie-response';

export interface GetGoalies$Params {}

export function getGoalies(
  http: HttpClient,
  rootUrl: string,
  params?: GetGoalies$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<GoalieResponse>>> {
  const rb = new RequestBuilder(rootUrl, getGoalies.PATH, 'get');
  if (params) {
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GoalieResponse>>;
    }),
  );
}

getGoalies.PATH = '/api/v1/players/goalies';
