/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Register$Params as Register$Params } from './fn/authentication/register';
export { register as register } from './fn/authentication/register';
export type { Login$Params as Login$Params } from './fn/authentication/login';
export { login as login } from './fn/authentication/login';
export type { GetSkaters$Params as GetSkaters$Params } from './fn/players/get-skaters';
export { getSkaters as getSkaters } from './fn/players/get-skaters';
export type { GetGoalies$Params as GetGoalies$Params } from './fn/players/get-goalies';
export { getGoalies as getGoalies } from './fn/players/get-goalies';
