/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthResponse } from './models/auth-response';
export type { GoalieResponse } from './models/goalie-response';
export type { LoginRequest } from './models/login-request';
export type { RegisterRequest } from './models/register-request';
export type { ScoringStats } from './models/scoring-stats';
export type { SkaterResponse } from './models/skater-response';
export type { Stats } from './models/stats';
export type { UtilityStats } from './models/utility-stats';
