/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthResponse {
  expiresInSeconds: number;
  refreshExpiresInSeconds: number;
  refreshToken: string;
  token: string;
}
