/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GoalieStats } from '../models/goalie-stats';
export interface GoalieResponse {
  id: number;
  name: string;
  stats: GoalieStats;
  type: 'skater' | 'goalie';
}
