/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GoalieScoringStats } from '../models/goalie-scoring-stats';
import { GoalieUtilityStats } from '../models/goalie-utility-stats';
export interface GoalieStats {
  scoring: GoalieScoringStats;
  utility: GoalieUtilityStats;
}
