/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GoalieScoringStats {
  ga: number;
  gaa: number;
  gs: number;
  l: number;
  sa: number;
  sho: number;
  sv: number;
  svPct: number;
  w: number;
}
