/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Stats } from '../models/stats';
export interface GoalieResponse {
  id?: number;
  name?: string;
  stats?: Stats;
  type?: string;
}
