/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SkaterStats } from '../models/skater-stats';
export interface SkaterResponse {
  id: number;
  name: string;
  positions: Array<string>;
  stats: SkaterStats;
  type: 'skater' | 'goalie';
}
