/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SkaterScoringStats {
  assists: number;
  blocks: number;
  fl: number;
  fw: number;
  goals: number;
  gwg: number;
  hits: number;
  pim: number;
  plusMinus: number;
  ppa: number;
  ppg: number;
  shPct: number;
  sha: number;
  shg: number;
  sog: number;
}
