/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Stats } from '../models/stats';
export interface SkaterResponse {
  id: number;
  name: string;
  positions: Array<string>;
  stats: Stats;
  type: 'skater' | 'goalie';
}
