/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SkaterScoringStats } from '../models/skater-scoring-stats';
import { SkaterUtilityStats } from '../models/skater-utility-stats';
export interface SkaterStats {
  scoring: SkaterScoringStats;
  utility: SkaterUtilityStats;
}
