/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScoringStats } from '../models/scoring-stats';
import { UtilityStats } from '../models/utility-stats';
export interface Stats {
  scoring: ScoringStats;
  utility: UtilityStats;
}
