import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Player } from '../models/player.model';

@Injectable({
  providedIn: 'root',
})
export class PlayerService {
  private readonly mockPlayers: Player[] = [
    {
      id: 1,
      name: 'Connor McDavid',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 82, toiPerGame: 1320 },
        scoring: {
          goals: 64,
          assists: 89,
          plusMinus: 33,
          pim: 36,
          ppg: 22,
          ppa: 38,
          shg: 1,
          sha: 0,
          gwg: 8,
          sog: 348,
          shPct: 18.4,
          fw: 812,
          fl: 623,
          hits: 42,
          blocks: 28,
        },
      },
    },
    {
      id: 2,
      name: 'Nathan MacKinnon',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 79, toiPerGame: 1305 },
        scoring: {
          goals: 51,
          assists: 83,
          plusMinus: 28,
          pim: 44,
          ppg: 19,
          ppa: 31,
          shg: 0,
          sha: 1,
          gwg: 7,
          sog: 312,
          shPct: 16.3,
          fw: 734,
          fl: 581,
          hits: 65,
          blocks: 35,
        },
      },
    },
    {
      id: 3,
      name: 'Auston Matthews',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 81, toiPerGame: 1230 },
        scoring: {
          goals: 69,
          assists: 54,
          plusMinus: 21,
          pim: 30,
          ppg: 24,
          ppa: 18,
          shg: 2,
          sha: 0,
          gwg: 9,
          sog: 371,
          shPct: 18.6,
          fw: 489,
          fl: 392,
          hits: 38,
          blocks: 22,
        },
      },
    },
    {
      id: 4,
      name: 'Leon Draisaitl',
      positions: new Set(['C', 'LW']),
      stats: {
        utility: { gp: 80, toiPerGame: 1260 },
        scoring: {
          goals: 52,
          assists: 76,
          plusMinus: 18,
          pim: 58,
          ppg: 21,
          ppa: 34,
          shg: 1,
          sha: 2,
          gwg: 6,
          sog: 298,
          shPct: 17.4,
          fw: 367,
          fl: 298,
          hits: 51,
          blocks: 19,
        },
      },
    },
    {
      id: 5,
      name: 'David Pastrnak',
      positions: new Set(['RW']),
      stats: {
        utility: { gp: 82, toiPerGame: 1170 },
        scoring: {
          goals: 61,
          assists: 68,
          plusMinus: 24,
          pim: 42,
          ppg: 25,
          ppa: 27,
          shg: 0,
          sha: 0,
          gwg: 8,
          sog: 334,
          shPct: 18.3,
          fw: 201,
          fl: 178,
          hits: 44,
          blocks: 31,
        },
      },
    },
    {
      id: 6,
      name: 'Nikita Kucherov',
      positions: new Set(['RW']),
      stats: {
        utility: { gp: 76, toiPerGame: 1275 },
        scoring: {
          goals: 44,
          assists: 100,
          plusMinus: 30,
          pim: 48,
          ppg: 18,
          ppa: 42,
          shg: 0,
          sha: 1,
          gwg: 5,
          sog: 256,
          shPct: 17.2,
          fw: 124,
          fl: 108,
          hits: 37,
          blocks: 25,
        },
      },
    },
    {
      id: 7,
      name: 'Cale Makar',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 77, toiPerGame: 1500 },
        scoring: {
          goals: 30,
          assists: 70,
          plusMinus: 35,
          pim: 28,
          ppg: 14,
          ppa: 32,
          shg: 1,
          sha: 0,
          gwg: 4,
          sog: 278,
          shPct: 10.8,
          fw: 0,
          fl: 0,
          hits: 58,
          blocks: 142,
        },
      },
    },
    {
      id: 8,
      name: 'Erik Karlsson',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 65, toiPerGame: 1470 },
        scoring: {
          goals: 22,
          assists: 63,
          plusMinus: -5,
          pim: 32,
          ppg: 11,
          ppa: 29,
          shg: 0,
          sha: 0,
          gwg: 3,
          sog: 212,
          shPct: 10.4,
          fw: 0,
          fl: 0,
          hits: 29,
          blocks: 98,
        },
      },
    },
    {
      id: 9,
      name: 'Roman Josi',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 82, toiPerGame: 1485 },
        scoring: {
          goals: 24,
          assists: 66,
          plusMinus: 14,
          pim: 36,
          ppg: 12,
          ppa: 28,
          shg: 0,
          sha: 1,
          gwg: 4,
          sog: 234,
          shPct: 10.3,
          fw: 0,
          fl: 0,
          hits: 63,
          blocks: 156,
        },
      },
    },
    {
      id: 10,
      name: 'Quinn Hughes',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 82, toiPerGame: 1530 },
        scoring: {
          goals: 18,
          assists: 72,
          plusMinus: 22,
          pim: 22,
          ppg: 9,
          ppa: 31,
          shg: 0,
          sha: 0,
          gwg: 2,
          sog: 198,
          shPct: 9.1,
          fw: 0,
          fl: 0,
          hits: 24,
          blocks: 112,
        },
      },
    },
    {
      id: 11,
      name: 'Brayden Point',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 82, toiPerGame: 1215 },
        scoring: {
          goals: 51,
          assists: 63,
          plusMinus: 20,
          pim: 40,
          ppg: 20,
          ppa: 22,
          shg: 3,
          sha: 1,
          gwg: 7,
          sog: 292,
          shPct: 17.5,
          fw: 556,
          fl: 421,
          hits: 55,
          blocks: 41,
        },
      },
    },
    {
      id: 12,
      name: 'Jason Robertson',
      positions: new Set(['LW', 'RW']),
      stats: {
        utility: { gp: 79, toiPerGame: 1185 },
        scoring: {
          goals: 46,
          assists: 63,
          plusMinus: 16,
          pim: 26,
          ppg: 17,
          ppa: 21,
          shg: 0,
          sha: 0,
          gwg: 6,
          sog: 267,
          shPct: 17.2,
          fw: 312,
          fl: 256,
          hits: 39,
          blocks: 27,
        },
      },
    },
    {
      id: 13,
      name: 'Mitch Marner',
      positions: new Set(['RW']),
      stats: {
        utility: { gp: 82, toiPerGame: 1200 },
        scoring: {
          goals: 37,
          assists: 82,
          plusMinus: 26,
          pim: 20,
          ppg: 13,
          ppa: 35,
          shg: 1,
          sha: 2,
          gwg: 5,
          sog: 234,
          shPct: 15.8,
          fw: 289,
          fl: 234,
          hits: 31,
          blocks: 38,
        },
      },
    },
    {
      id: 14,
      name: 'Aleksander Barkov',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 80, toiPerGame: 1290 },
        scoring: {
          goals: 39,
          assists: 72,
          plusMinus: 22,
          pim: 34,
          ppg: 14,
          ppa: 26,
          shg: 4,
          sha: 3,
          gwg: 6,
          sog: 245,
          shPct: 15.9,
          fw: 1102,
          fl: 712,
          hits: 48,
          blocks: 52,
        },
      },
    },
    {
      id: 15,
      name: 'Bo Horvat',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 82, toiPerGame: 1125 },
        scoring: {
          goals: 44,
          assists: 48,
          plusMinus: 10,
          pim: 52,
          ppg: 16,
          ppa: 14,
          shg: 2,
          sha: 1,
          gwg: 7,
          sog: 234,
          shPct: 18.8,
          fw: 978,
          fl: 734,
          hits: 87,
          blocks: 44,
        },
      },
    },
    {
      id: 16,
      name: 'Kirill Kaprizov',
      positions: new Set(['LW']),
      stats: {
        utility: { gp: 81, toiPerGame: 1245 },
        scoring: {
          goals: 55,
          assists: 64,
          plusMinus: 19,
          pim: 38,
          ppg: 19,
          ppa: 24,
          shg: 0,
          sha: 0,
          gwg: 8,
          sog: 312,
          shPct: 17.6,
          fw: 178,
          fl: 142,
          hits: 43,
          blocks: 29,
        },
      },
    },
    {
      id: 17,
      name: 'Sebastian Aho',
      positions: new Set(['C', 'LW']),
      stats: {
        utility: { gp: 82, toiPerGame: 1155 },
        scoring: {
          goals: 42,
          assists: 64,
          plusMinus: 12,
          pim: 44,
          ppg: 15,
          ppa: 22,
          shg: 3,
          sha: 2,
          gwg: 5,
          sog: 263,
          shPct: 16.0,
          fw: 634,
          fl: 498,
          hits: 61,
          blocks: 47,
        },
      },
    },
    {
      id: 18,
      name: 'Jake Guentzel',
      positions: new Set(['LW']),
      stats: {
        utility: { gp: 78, toiPerGame: 1110 },
        scoring: {
          goals: 44,
          assists: 49,
          plusMinus: 14,
          pim: 28,
          ppg: 16,
          ppa: 18,
          shg: 1,
          sha: 0,
          gwg: 6,
          sog: 248,
          shPct: 17.7,
          fw: 134,
          fl: 112,
          hits: 52,
          blocks: 33,
        },
      },
    },
    {
      id: 19,
      name: 'Mark Scheifele',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 80, toiPerGame: 1140 },
        scoring: {
          goals: 38,
          assists: 61,
          plusMinus: 8,
          pim: 46,
          ppg: 14,
          ppa: 20,
          shg: 2,
          sha: 1,
          gwg: 4,
          sog: 228,
          shPct: 16.7,
          fw: 812,
          fl: 634,
          hits: 46,
          blocks: 36,
        },
      },
    },
    {
      id: 20,
      name: 'Tage Thompson',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 82, toiPerGame: 1200 },
        scoring: {
          goals: 47,
          assists: 55,
          plusMinus: 15,
          pim: 56,
          ppg: 17,
          ppa: 19,
          shg: 1,
          sha: 0,
          gwg: 7,
          sog: 278,
          shPct: 16.9,
          fw: 289,
          fl: 234,
          hits: 74,
          blocks: 39,
        },
      },
    },
    {
      id: 21,
      name: 'Artemi Panarin',
      positions: new Set(['LW']),
      stats: {
        utility: { gp: 78, toiPerGame: 1230 },
        scoring: {
          goals: 38,
          assists: 74,
          plusMinus: 17,
          pim: 32,
          ppg: 16,
          ppa: 31,
          shg: 0,
          sha: 0,
          gwg: 5,
          sog: 224,
          shPct: 16.9,
          fw: 145,
          fl: 121,
          hits: 29,
          blocks: 22,
        },
      },
    },
    {
      id: 22,
      name: 'Matthew Tkachuk',
      positions: new Set(['LW']),
      stats: {
        utility: { gp: 80, toiPerGame: 1215 },
        scoring: {
          goals: 40,
          assists: 69,
          plusMinus: 20,
          pim: 86,
          ppg: 15,
          ppa: 28,
          shg: 1,
          sha: 0,
          gwg: 6,
          sog: 238,
          shPct: 16.8,
          fw: 201,
          fl: 167,
          hits: 112,
          blocks: 41,
        },
      },
    },
    {
      id: 23,
      name: 'Brady Tkachuk',
      positions: new Set(['LW']),
      stats: {
        utility: { gp: 79, toiPerGame: 1170 },
        scoring: {
          goals: 37,
          assists: 45,
          plusMinus: -2,
          pim: 124,
          ppg: 11,
          ppa: 14,
          shg: 2,
          sha: 1,
          gwg: 5,
          sog: 218,
          shPct: 17.0,
          fw: 178,
          fl: 156,
          hits: 178,
          blocks: 56,
        },
      },
    },
    {
      id: 24,
      name: 'Clayton Keller',
      positions: new Set(['C', 'RW']),
      stats: {
        utility: { gp: 82, toiPerGame: 1185 },
        scoring: {
          goals: 43,
          assists: 60,
          plusMinus: 8,
          pim: 28,
          ppg: 15,
          ppa: 22,
          shg: 1,
          sha: 0,
          gwg: 6,
          sog: 252,
          shPct: 17.1,
          fw: 334,
          fl: 267,
          hits: 38,
          blocks: 31,
        },
      },
    },
    {
      id: 25,
      name: 'Elias Pettersson',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 80, toiPerGame: 1200 },
        scoring: {
          goals: 41,
          assists: 63,
          plusMinus: 15,
          pim: 36,
          ppg: 16,
          ppa: 25,
          shg: 2,
          sha: 1,
          gwg: 5,
          sog: 241,
          shPct: 17.0,
          fw: 489,
          fl: 378,
          hits: 34,
          blocks: 28,
        },
      },
    },
    {
      id: 26,
      name: 'Kyle Connor',
      positions: new Set(['LW']),
      stats: {
        utility: { gp: 78, toiPerGame: 1125 },
        scoring: {
          goals: 42,
          assists: 46,
          plusMinus: 6,
          pim: 22,
          ppg: 14,
          ppa: 16,
          shg: 1,
          sha: 0,
          gwg: 7,
          sog: 245,
          shPct: 17.1,
          fw: 112,
          fl: 89,
          hits: 33,
          blocks: 24,
        },
      },
    },
    {
      id: 27,
      name: 'Aleksander Romanov',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 76, toiPerGame: 1395 },
        scoring: {
          goals: 8,
          assists: 34,
          plusMinus: 12,
          pim: 44,
          ppg: 3,
          ppa: 14,
          shg: 0,
          sha: 1,
          gwg: 1,
          sog: 112,
          shPct: 7.1,
          fw: 0,
          fl: 0,
          hits: 134,
          blocks: 134,
        },
      },
    },
    {
      id: 28,
      name: 'Adam Fox',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 82, toiPerGame: 1455 },
        scoring: {
          goals: 14,
          assists: 61,
          plusMinus: 18,
          pim: 18,
          ppg: 7,
          ppa: 26,
          shg: 0,
          sha: 0,
          gwg: 2,
          sog: 178,
          shPct: 7.9,
          fw: 0,
          fl: 0,
          hits: 31,
          blocks: 128,
        },
      },
    },
    {
      id: 29,
      name: 'Rasmus Dahlin',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 79, toiPerGame: 1440 },
        scoring: {
          goals: 16,
          assists: 58,
          plusMinus: 10,
          pim: 26,
          ppg: 8,
          ppa: 24,
          shg: 0,
          sha: 0,
          gwg: 2,
          sog: 189,
          shPct: 8.5,
          fw: 0,
          fl: 0,
          hits: 45,
          blocks: 119,
        },
      },
    },
    {
      id: 30,
      name: 'Dougie Hamilton',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 76, toiPerGame: 1410 },
        scoring: {
          goals: 17,
          assists: 52,
          plusMinus: 8,
          pim: 34,
          ppg: 9,
          ppa: 22,
          shg: 0,
          sha: 0,
          gwg: 3,
          sog: 196,
          shPct: 8.7,
          fw: 0,
          fl: 0,
          hits: 52,
          blocks: 104,
        },
      },
    },
    {
      id: 31,
      name: 'Victor Hedman',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 77, toiPerGame: 1500 },
        scoring: {
          goals: 12,
          assists: 55,
          plusMinus: 16,
          pim: 30,
          ppg: 6,
          ppa: 24,
          shg: 1,
          sha: 2,
          gwg: 2,
          sog: 156,
          shPct: 7.7,
          fw: 0,
          fl: 0,
          hits: 67,
          blocks: 148,
        },
      },
    },
    {
      id: 32,
      name: 'Miro Heiskanen',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 82, toiPerGame: 1470 },
        scoring: {
          goals: 15,
          assists: 53,
          plusMinus: 13,
          pim: 22,
          ppg: 7,
          ppa: 21,
          shg: 1,
          sha: 0,
          gwg: 2,
          sog: 174,
          shPct: 8.6,
          fw: 0,
          fl: 0,
          hits: 41,
          blocks: 138,
        },
      },
    },
    {
      id: 33,
      name: 'John Carlson',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 74, toiPerGame: 1380 },
        scoring: {
          goals: 11,
          assists: 48,
          plusMinus: 5,
          pim: 20,
          ppg: 6,
          ppa: 20,
          shg: 0,
          sha: 0,
          gwg: 1,
          sog: 144,
          shPct: 7.6,
          fw: 0,
          fl: 0,
          hits: 28,
          blocks: 98,
        },
      },
    },
    {
      id: 34,
      name: 'Alex Pietrangelo',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 71, toiPerGame: 1425 },
        scoring: {
          goals: 10,
          assists: 42,
          plusMinus: 9,
          pim: 28,
          ppg: 5,
          ppa: 18,
          shg: 0,
          sha: 1,
          gwg: 1,
          sog: 138,
          shPct: 7.2,
          fw: 0,
          fl: 0,
          hits: 56,
          blocks: 112,
        },
      },
    },
    {
      id: 35,
      name: 'Cam Atkinson',
      positions: new Set(['RW']),
      stats: {
        utility: { gp: 75, toiPerGame: 1080 },
        scoring: {
          goals: 34,
          assists: 38,
          plusMinus: 4,
          pim: 32,
          ppg: 12,
          ppa: 12,
          shg: 1,
          sha: 0,
          gwg: 5,
          sog: 218,
          shPct: 15.6,
          fw: 112,
          fl: 98,
          hits: 48,
          blocks: 29,
        },
      },
    },
    {
      id: 36,
      name: 'Jonathan Huberdeau',
      positions: new Set(['LW']),
      stats: {
        utility: { gp: 80, toiPerGame: 1185 },
        scoring: {
          goals: 28,
          assists: 65,
          plusMinus: 6,
          pim: 30,
          ppg: 11,
          ppa: 26,
          shg: 0,
          sha: 0,
          gwg: 4,
          sog: 189,
          shPct: 14.8,
          fw: 167,
          fl: 134,
          hits: 35,
          blocks: 26,
        },
      },
    },
    {
      id: 37,
      name: 'Mikko Rantanen',
      positions: new Set(['RW']),
      stats: {
        utility: { gp: 81, toiPerGame: 1200 },
        scoring: {
          goals: 45,
          assists: 66,
          plusMinus: 22,
          pim: 40,
          ppg: 17,
          ppa: 26,
          shg: 0,
          sha: 0,
          gwg: 6,
          sog: 267,
          shPct: 16.9,
          fw: 156,
          fl: 134,
          hits: 56,
          blocks: 34,
        },
      },
    },
    {
      id: 38,
      name: 'Sean Couturier',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 77, toiPerGame: 1230 },
        scoring: {
          goals: 28,
          assists: 49,
          plusMinus: 14,
          pim: 38,
          ppg: 8,
          ppa: 14,
          shg: 5,
          sha: 3,
          gwg: 4,
          sog: 198,
          shPct: 14.1,
          fw: 1045,
          fl: 789,
          hits: 62,
          blocks: 68,
        },
      },
    },
    {
      id: 39,
      name: 'Anze Kopitar',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 82, toiPerGame: 1260 },
        scoring: {
          goals: 27,
          assists: 55,
          plusMinus: 18,
          pim: 22,
          ppg: 9,
          ppa: 16,
          shg: 4,
          sha: 2,
          gwg: 5,
          sog: 201,
          shPct: 13.4,
          fw: 934,
          fl: 712,
          hits: 44,
          blocks: 54,
        },
      },
    },
    {
      id: 40,
      name: 'Steven Stamkos',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 74, toiPerGame: 1170 },
        scoring: {
          goals: 39,
          assists: 46,
          plusMinus: 10,
          pim: 34,
          ppg: 16,
          ppa: 17,
          shg: 0,
          sha: 0,
          gwg: 6,
          sog: 234,
          shPct: 16.7,
          fw: 312,
          fl: 256,
          hits: 41,
          blocks: 32,
        },
      },
    },
    {
      id: 41,
      name: 'Gabriel Landeskog',
      positions: new Set(['LW']),
      stats: {
        utility: { gp: 65, toiPerGame: 1155 },
        scoring: {
          goals: 28,
          assists: 42,
          plusMinus: 12,
          pim: 62,
          ppg: 9,
          ppa: 14,
          shg: 1,
          sha: 0,
          gwg: 4,
          sog: 189,
          shPct: 14.8,
          fw: 189,
          fl: 156,
          hits: 89,
          blocks: 38,
        },
      },
    },
    {
      id: 42,
      name: 'Patrice Bergeron',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 78, toiPerGame: 1215 },
        scoring: {
          goals: 24,
          assists: 46,
          plusMinus: 16,
          pim: 20,
          ppg: 7,
          ppa: 12,
          shg: 6,
          sha: 4,
          gwg: 4,
          sog: 189,
          shPct: 12.7,
          fw: 1289,
          fl: 956,
          hits: 38,
          blocks: 58,
        },
      },
    },
    {
      id: 43,
      name: 'Alex Ovechkin',
      positions: new Set(['LW']),
      stats: {
        utility: { gp: 73, toiPerGame: 1125 },
        scoring: {
          goals: 42,
          assists: 34,
          plusMinus: -4,
          pim: 44,
          ppg: 18,
          ppa: 14,
          shg: 0,
          sha: 0,
          gwg: 7,
          sog: 289,
          shPct: 14.5,
          fw: 78,
          fl: 67,
          hits: 78,
          blocks: 22,
        },
      },
    },
    {
      id: 44,
      name: 'Sidney Crosby',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 80, toiPerGame: 1245 },
        scoring: {
          goals: 35,
          assists: 64,
          plusMinus: 14,
          pim: 38,
          ppg: 13,
          ppa: 22,
          shg: 2,
          sha: 1,
          gwg: 5,
          sog: 245,
          shPct: 14.3,
          fw: 812,
          fl: 634,
          hits: 56,
          blocks: 44,
        },
      },
    },
    {
      id: 45,
      name: 'Jonathan Toews',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 71, toiPerGame: 1185 },
        scoring: {
          goals: 22,
          assists: 39,
          plusMinus: 4,
          pim: 34,
          ppg: 7,
          ppa: 11,
          shg: 3,
          sha: 2,
          gwg: 3,
          sog: 167,
          shPct: 13.2,
          fw: 978,
          fl: 756,
          hits: 52,
          blocks: 48,
        },
      },
    },
    {
      id: 46,
      name: 'Evgeni Malkin',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 69, toiPerGame: 1200 },
        scoring: {
          goals: 31,
          assists: 54,
          plusMinus: 8,
          pim: 52,
          ppg: 13,
          ppa: 22,
          shg: 1,
          sha: 0,
          gwg: 4,
          sog: 212,
          shPct: 14.6,
          fw: 445,
          fl: 356,
          hits: 47,
          blocks: 36,
        },
      },
    },
    {
      id: 47,
      name: 'Claude Giroux',
      positions: new Set(['C', 'LW']),
      stats: {
        utility: { gp: 82, toiPerGame: 1185 },
        scoring: {
          goals: 28,
          assists: 58,
          plusMinus: 10,
          pim: 28,
          ppg: 10,
          ppa: 21,
          shg: 1,
          sha: 1,
          gwg: 4,
          sog: 196,
          shPct: 14.3,
          fw: 712,
          fl: 556,
          hits: 48,
          blocks: 41,
        },
      },
    },
    {
      id: 48,
      name: "Ryan O'Reilly",
      positions: new Set(['C']),
      stats: {
        utility: { gp: 80, toiPerGame: 1215 },
        scoring: {
          goals: 24,
          assists: 52,
          plusMinus: 12,
          pim: 36,
          ppg: 8,
          ppa: 16,
          shg: 5,
          sha: 3,
          gwg: 4,
          sog: 189,
          shPct: 12.7,
          fw: 1134,
          fl: 867,
          hits: 58,
          blocks: 56,
        },
      },
    },
    {
      id: 49,
      name: 'Vincent Trocheck',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 80, toiPerGame: 1155 },
        scoring: {
          goals: 28,
          assists: 47,
          plusMinus: 6,
          pim: 48,
          ppg: 9,
          ppa: 14,
          shg: 2,
          sha: 2,
          gwg: 4,
          sog: 196,
          shPct: 14.3,
          fw: 867,
          fl: 656,
          hits: 72,
          blocks: 44,
        },
      },
    },
    {
      id: 50,
      name: 'Sam Reinhart',
      positions: new Set(['C', 'RW']),
      stats: {
        utility: { gp: 81, toiPerGame: 1155 },
        scoring: {
          goals: 40,
          assists: 50,
          plusMinus: 14,
          pim: 24,
          ppg: 14,
          ppa: 18,
          shg: 1,
          sha: 0,
          gwg: 6,
          sog: 234,
          shPct: 17.1,
          fw: 312,
          fl: 256,
          hits: 44,
          blocks: 31,
        },
      },
    },
    {
      id: 51,
      name: 'Roope Hintz',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 79, toiPerGame: 1140 },
        scoring: {
          goals: 37,
          assists: 48,
          plusMinus: 11,
          pim: 32,
          ppg: 13,
          ppa: 15,
          shg: 1,
          sha: 0,
          gwg: 5,
          sog: 218,
          shPct: 17.0,
          fw: 467,
          fl: 356,
          hits: 52,
          blocks: 36,
        },
      },
    },
    {
      id: 52,
      name: 'Nazem Kadri',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 75, toiPerGame: 1155 },
        scoring: {
          goals: 33,
          assists: 50,
          plusMinus: 8,
          pim: 64,
          ppg: 11,
          ppa: 18,
          shg: 1,
          sha: 0,
          gwg: 5,
          sog: 212,
          shPct: 15.6,
          fw: 578,
          fl: 445,
          hits: 67,
          blocks: 42,
        },
      },
    },
    {
      id: 53,
      name: 'Jordan Kyrou',
      positions: new Set(['RW']),
      stats: {
        utility: { gp: 77, toiPerGame: 1110 },
        scoring: {
          goals: 35,
          assists: 48,
          plusMinus: 7,
          pim: 28,
          ppg: 11,
          ppa: 16,
          shg: 0,
          sha: 0,
          gwg: 5,
          sog: 221,
          shPct: 15.8,
          fw: 134,
          fl: 112,
          hits: 41,
          blocks: 28,
        },
      },
    },
    {
      id: 54,
      name: 'Rickard Rakell',
      positions: new Set(['C', 'LW']),
      stats: {
        utility: { gp: 79, toiPerGame: 1110 },
        scoring: {
          goals: 32,
          assists: 41,
          plusMinus: 6,
          pim: 36,
          ppg: 11,
          ppa: 13,
          shg: 1,
          sha: 0,
          gwg: 5,
          sog: 208,
          shPct: 15.4,
          fw: 289,
          fl: 234,
          hits: 55,
          blocks: 33,
        },
      },
    },
    {
      id: 55,
      name: 'Rickard Gudas',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 80, toiPerGame: 1350 },
        scoring: {
          goals: 6,
          assists: 24,
          plusMinus: 2,
          pim: 68,
          ppg: 2,
          ppa: 8,
          shg: 0,
          sha: 0,
          gwg: 1,
          sog: 98,
          shPct: 6.1,
          fw: 0,
          fl: 0,
          hits: 178,
          blocks: 112,
        },
      },
    },
    {
      id: 56,
      name: 'Shea Theodore',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 76, toiPerGame: 1380 },
        scoring: {
          goals: 14,
          assists: 46,
          plusMinus: 7,
          pim: 24,
          ppg: 7,
          ppa: 19,
          shg: 0,
          sha: 0,
          gwg: 2,
          sog: 162,
          shPct: 8.6,
          fw: 0,
          fl: 0,
          hits: 48,
          blocks: 108,
        },
      },
    },
    {
      id: 57,
      name: 'Morgan Rielly',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 79, toiPerGame: 1410 },
        scoring: {
          goals: 12,
          assists: 48,
          plusMinus: 6,
          pim: 22,
          ppg: 6,
          ppa: 19,
          shg: 0,
          sha: 0,
          gwg: 1,
          sog: 148,
          shPct: 8.1,
          fw: 0,
          fl: 0,
          hits: 38,
          blocks: 116,
        },
      },
    },
    {
      id: 58,
      name: 'Darnell Nurse',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 78, toiPerGame: 1440 },
        scoring: {
          goals: 11,
          assists: 34,
          plusMinus: 4,
          pim: 56,
          ppg: 4,
          ppa: 12,
          shg: 1,
          sha: 0,
          gwg: 2,
          sog: 134,
          shPct: 8.2,
          fw: 0,
          fl: 0,
          hits: 167,
          blocks: 124,
        },
      },
    },
    {
      id: 59,
      name: 'Matt Dumba',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 71, toiPerGame: 1335 },
        scoring: {
          goals: 12,
          assists: 31,
          plusMinus: 1,
          pim: 48,
          ppg: 5,
          ppa: 12,
          shg: 0,
          sha: 0,
          gwg: 2,
          sog: 148,
          shPct: 8.1,
          fw: 0,
          fl: 0,
          hits: 112,
          blocks: 98,
        },
      },
    },
    {
      id: 60,
      name: 'Zach Werenski',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 78, toiPerGame: 1380 },
        scoring: {
          goals: 16,
          assists: 44,
          plusMinus: 3,
          pim: 26,
          ppg: 8,
          ppa: 17,
          shg: 0,
          sha: 0,
          gwg: 2,
          sog: 178,
          shPct: 9.0,
          fw: 0,
          fl: 0,
          hits: 36,
          blocks: 104,
        },
      },
    },
    {
      id: 61,
      name: 'Brent Burns',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 76, toiPerGame: 1425 },
        scoring: {
          goals: 13,
          assists: 40,
          plusMinus: -3,
          pim: 46,
          ppg: 6,
          ppa: 16,
          shg: 0,
          sha: 0,
          gwg: 2,
          sog: 189,
          shPct: 6.9,
          fw: 0,
          fl: 0,
          hits: 62,
          blocks: 119,
        },
      },
    },
    {
      id: 62,
      name: 'Drew Doughty',
      positions: new Set(['D']),
      stats: {
        utility: { gp: 75, toiPerGame: 1470 },
        scoring: {
          goals: 9,
          assists: 38,
          plusMinus: 2,
          pim: 38,
          ppg: 4,
          ppa: 14,
          shg: 0,
          sha: 1,
          gwg: 1,
          sog: 138,
          shPct: 6.5,
          fw: 0,
          fl: 0,
          hits: 78,
          blocks: 134,
        },
      },
    },
    {
      id: 63,
      name: 'Filip Forsberg',
      positions: new Set(['LW']),
      stats: {
        utility: { gp: 69, toiPerGame: 1155 },
        scoring: {
          goals: 38,
          assists: 42,
          plusMinus: 10,
          pim: 36,
          ppg: 14,
          ppa: 16,
          shg: 0,
          sha: 0,
          gwg: 6,
          sog: 234,
          shPct: 16.2,
          fw: 145,
          fl: 112,
          hits: 52,
          blocks: 28,
        },
      },
    },
    {
      id: 64,
      name: 'Aleksander Barkov Jr',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 76, toiPerGame: 1185 },
        scoring: {
          goals: 31,
          assists: 47,
          plusMinus: 12,
          pim: 30,
          ppg: 10,
          ppa: 17,
          shg: 3,
          sha: 1,
          gwg: 4,
          sog: 201,
          shPct: 15.4,
          fw: 678,
          fl: 523,
          hits: 44,
          blocks: 40,
        },
      },
    },
    {
      id: 65,
      name: 'Warren Foegele',
      positions: new Set(['LW']),
      stats: {
        utility: { gp: 78, toiPerGame: 1080 },
        scoring: {
          goals: 26,
          assists: 28,
          plusMinus: 5,
          pim: 58,
          ppg: 7,
          ppa: 8,
          shg: 1,
          sha: 0,
          gwg: 4,
          sog: 178,
          shPct: 14.6,
          fw: 112,
          fl: 89,
          hits: 134,
          blocks: 31,
        },
      },
    },
    {
      id: 66,
      name: 'William Nylander',
      positions: new Set(['RW', 'C']),
      stats: {
        utility: { gp: 82, toiPerGame: 1155 },
        scoring: {
          goals: 40,
          assists: 56,
          plusMinus: 18,
          pim: 22,
          ppg: 15,
          ppa: 20,
          shg: 0,
          sha: 0,
          gwg: 6,
          sog: 248,
          shPct: 16.1,
          fw: 178,
          fl: 145,
          hits: 29,
          blocks: 24,
        },
      },
    },
    {
      id: 67,
      name: 'Alex DeBrincat',
      positions: new Set(['LW']),
      stats: {
        utility: { gp: 77, toiPerGame: 1110 },
        scoring: {
          goals: 41,
          assists: 44,
          plusMinus: 7,
          pim: 24,
          ppg: 16,
          ppa: 16,
          shg: 0,
          sha: 0,
          gwg: 6,
          sog: 241,
          shPct: 17.0,
          fw: 112,
          fl: 89,
          hits: 33,
          blocks: 21,
        },
      },
    },
    {
      id: 68,
      name: 'Nick Suzuki',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 82, toiPerGame: 1185 },
        scoring: {
          goals: 30,
          assists: 58,
          plusMinus: 8,
          pim: 32,
          ppg: 11,
          ppa: 22,
          shg: 1,
          sha: 0,
          gwg: 4,
          sog: 212,
          shPct: 14.2,
          fw: 556,
          fl: 423,
          hits: 42,
          blocks: 34,
        },
      },
    },
    {
      id: 69,
      name: 'Ilya Mikheyev',
      positions: new Set(['RW']),
      stats: {
        utility: { gp: 74, toiPerGame: 1080 },
        scoring: {
          goals: 28,
          assists: 32,
          plusMinus: 9,
          pim: 18,
          ppg: 7,
          ppa: 9,
          shg: 2,
          sha: 0,
          gwg: 4,
          sog: 178,
          shPct: 15.7,
          fw: 89,
          fl: 78,
          hits: 55,
          blocks: 28,
        },
      },
    },
    {
      id: 70,
      name: 'Ryan Nugent-Hopkins',
      positions: new Set(['C', 'LW']),
      stats: {
        utility: { gp: 80, toiPerGame: 1170 },
        scoring: {
          goals: 30,
          assists: 56,
          plusMinus: 11,
          pim: 30,
          ppg: 11,
          ppa: 21,
          shg: 3,
          sha: 1,
          gwg: 4,
          sog: 208,
          shPct: 14.4,
          fw: 489,
          fl: 378,
          hits: 46,
          blocks: 38,
        },
      },
    },
    {
      id: 71,
      name: 'Elias Lindholm',
      positions: new Set(['C', 'RW']),
      stats: {
        utility: { gp: 82, toiPerGame: 1185 },
        scoring: {
          goals: 32,
          assists: 48,
          plusMinus: 10,
          pim: 28,
          ppg: 10,
          ppa: 16,
          shg: 3,
          sha: 1,
          gwg: 5,
          sog: 214,
          shPct: 15.0,
          fw: 712,
          fl: 556,
          hits: 48,
          blocks: 42,
        },
      },
    },
    {
      id: 72,
      name: 'Chris Kreider',
      positions: new Set(['LW']),
      stats: {
        utility: { gp: 79, toiPerGame: 1110 },
        scoring: {
          goals: 38,
          assists: 36,
          plusMinus: 9,
          pim: 44,
          ppg: 16,
          ppa: 11,
          shg: 1,
          sha: 0,
          gwg: 7,
          sog: 228,
          shPct: 16.7,
          fw: 112,
          fl: 89,
          hits: 89,
          blocks: 32,
        },
      },
    },
    {
      id: 73,
      name: 'Mark Stone',
      positions: new Set(['RW']),
      stats: {
        utility: { gp: 62, toiPerGame: 1170 },
        scoring: {
          goals: 23,
          assists: 42,
          plusMinus: 10,
          pim: 22,
          ppg: 8,
          ppa: 16,
          shg: 2,
          sha: 1,
          gwg: 3,
          sog: 178,
          shPct: 12.9,
          fw: 134,
          fl: 112,
          hits: 44,
          blocks: 36,
        },
      },
    },
    {
      id: 74,
      name: 'Tomas Hertl',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 76, toiPerGame: 1170 },
        scoring: {
          goals: 33,
          assists: 44,
          plusMinus: 8,
          pim: 36,
          ppg: 11,
          ppa: 15,
          shg: 1,
          sha: 0,
          gwg: 5,
          sog: 208,
          shPct: 15.9,
          fw: 534,
          fl: 412,
          hits: 62,
          blocks: 44,
        },
      },
    },
    {
      id: 75,
      name: 'Kevin Hayes',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 77, toiPerGame: 1125 },
        scoring: {
          goals: 22,
          assists: 44,
          plusMinus: 2,
          pim: 40,
          ppg: 7,
          ppa: 15,
          shg: 1,
          sha: 1,
          gwg: 3,
          sog: 178,
          shPct: 12.4,
          fw: 534,
          fl: 412,
          hits: 56,
          blocks: 38,
        },
      },
    },
    {
      id: 76,
      name: 'Oliver Bjorkstrand',
      positions: new Set(['RW']),
      stats: {
        utility: { gp: 74, toiPerGame: 1095 },
        scoring: {
          goals: 30,
          assists: 38,
          plusMinus: 6,
          pim: 22,
          ppg: 10,
          ppa: 12,
          shg: 1,
          sha: 0,
          gwg: 4,
          sog: 196,
          shPct: 15.3,
          fw: 89,
          fl: 67,
          hits: 38,
          blocks: 24,
        },
      },
    },
    {
      id: 77,
      name: 'Patrik Laine',
      positions: new Set(['LW', 'RW']),
      stats: {
        utility: { gp: 68, toiPerGame: 1110 },
        scoring: {
          goals: 36,
          assists: 38,
          plusMinus: 2,
          pim: 34,
          ppg: 14,
          ppa: 14,
          shg: 0,
          sha: 0,
          gwg: 5,
          sog: 224,
          shPct: 16.1,
          fw: 89,
          fl: 78,
          hits: 34,
          blocks: 19,
        },
      },
    },
    {
      id: 78,
      name: 'Evander Kane',
      positions: new Set(['LW']),
      stats: {
        utility: { gp: 71, toiPerGame: 1110 },
        scoring: {
          goals: 35,
          assists: 30,
          plusMinus: 5,
          pim: 82,
          ppg: 12,
          ppa: 9,
          shg: 0,
          sha: 0,
          gwg: 6,
          sog: 221,
          shPct: 15.8,
          fw: 98,
          fl: 89,
          hits: 98,
          blocks: 28,
        },
      },
    },
    {
      id: 79,
      name: 'Jonathan Marchessault',
      positions: new Set(['LW', 'RW']),
      stats: {
        utility: { gp: 79, toiPerGame: 1125 },
        scoring: {
          goals: 34,
          assists: 44,
          plusMinus: 9,
          pim: 34,
          ppg: 12,
          ppa: 16,
          shg: 2,
          sha: 0,
          gwg: 5,
          sog: 212,
          shPct: 16.0,
          fw: 134,
          fl: 112,
          hits: 56,
          blocks: 31,
        },
      },
    },
    {
      id: 80,
      name: 'Brock Nelson',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 80, toiPerGame: 1140 },
        scoring: {
          goals: 36,
          assists: 38,
          plusMinus: 7,
          pim: 30,
          ppg: 12,
          ppa: 12,
          shg: 1,
          sha: 0,
          gwg: 5,
          sog: 218,
          shPct: 16.5,
          fw: 456,
          fl: 345,
          hits: 52,
          blocks: 36,
        },
      },
    },
    {
      id: 81,
      name: 'Jakub Voracek',
      positions: new Set(['RW']),
      stats: {
        utility: { gp: 56, toiPerGame: 1095 },
        scoring: {
          goals: 16,
          assists: 38,
          plusMinus: 4,
          pim: 22,
          ppg: 6,
          ppa: 14,
          shg: 0,
          sha: 0,
          gwg: 2,
          sog: 134,
          shPct: 11.9,
          fw: 89,
          fl: 78,
          hits: 34,
          blocks: 26,
        },
      },
    },
    {
      id: 82,
      name: 'Carter Verhaeghe',
      positions: new Set(['LW', 'C']),
      stats: {
        utility: { gp: 79, toiPerGame: 1110 },
        scoring: {
          goals: 38,
          assists: 41,
          plusMinus: 12,
          pim: 26,
          ppg: 13,
          ppa: 14,
          shg: 1,
          sha: 0,
          gwg: 6,
          sog: 224,
          shPct: 17.0,
          fw: 201,
          fl: 167,
          hits: 48,
          blocks: 28,
        },
      },
    },
    {
      id: 83,
      name: 'Tom Wilson',
      positions: new Set(['RW']),
      stats: {
        utility: { gp: 74, toiPerGame: 1125 },
        scoring: {
          goals: 28,
          assists: 36,
          plusMinus: 8,
          pim: 92,
          ppg: 9,
          ppa: 11,
          shg: 0,
          sha: 0,
          gwg: 4,
          sog: 196,
          shPct: 14.3,
          fw: 134,
          fl: 112,
          hits: 189,
          blocks: 34,
        },
      },
    },
    {
      id: 84,
      name: 'Rickard Rakell',
      positions: new Set(['LW', 'C']),
      stats: {
        utility: { gp: 76, toiPerGame: 1110 },
        scoring: {
          goals: 30,
          assists: 38,
          plusMinus: 6,
          pim: 32,
          ppg: 10,
          ppa: 12,
          shg: 1,
          sha: 0,
          gwg: 4,
          sog: 201,
          shPct: 14.9,
          fw: 245,
          fl: 189,
          hits: 52,
          blocks: 31,
        },
      },
    },
    {
      id: 85,
      name: 'Tyler Toffoli',
      positions: new Set(['RW']),
      stats: {
        utility: { gp: 80, toiPerGame: 1095 },
        scoring: {
          goals: 33,
          assists: 36,
          plusMinus: 5,
          pim: 20,
          ppg: 11,
          ppa: 12,
          shg: 1,
          sha: 0,
          gwg: 5,
          sog: 208,
          shPct: 15.9,
          fw: 112,
          fl: 89,
          hits: 38,
          blocks: 26,
        },
      },
    },
    {
      id: 86,
      name: 'Tyler Bertuzzi',
      positions: new Set(['LW']),
      stats: {
        utility: { gp: 72, toiPerGame: 1095 },
        scoring: {
          goals: 29,
          assists: 34,
          plusMinus: 4,
          pim: 52,
          ppg: 9,
          ppa: 10,
          shg: 1,
          sha: 0,
          gwg: 4,
          sog: 189,
          shPct: 15.3,
          fw: 145,
          fl: 112,
          hits: 112,
          blocks: 29,
        },
      },
    },
    {
      id: 87,
      name: 'Jesperi Kotkaniemi',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 78, toiPerGame: 1125 },
        scoring: {
          goals: 24,
          assists: 40,
          plusMinus: 3,
          pim: 38,
          ppg: 7,
          ppa: 13,
          shg: 1,
          sha: 0,
          gwg: 3,
          sog: 178,
          shPct: 13.5,
          fw: 489,
          fl: 378,
          hits: 62,
          blocks: 38,
        },
      },
    },
    {
      id: 88,
      name: 'Jake DeBrusk',
      positions: new Set(['LW', 'RW']),
      stats: {
        utility: { gp: 76, toiPerGame: 1080 },
        scoring: {
          goals: 27,
          assists: 32,
          plusMinus: 3,
          pim: 38,
          ppg: 8,
          ppa: 10,
          shg: 1,
          sha: 0,
          gwg: 4,
          sog: 184,
          shPct: 14.7,
          fw: 89,
          fl: 78,
          hits: 67,
          blocks: 28,
        },
      },
    },
    {
      id: 89,
      name: 'Anthony Cirelli',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 80, toiPerGame: 1155 },
        scoring: {
          goals: 22,
          assists: 36,
          plusMinus: 14,
          pim: 34,
          ppg: 5,
          ppa: 9,
          shg: 4,
          sha: 2,
          gwg: 3,
          sog: 178,
          shPct: 12.4,
          fw: 712,
          fl: 534,
          hits: 78,
          blocks: 52,
        },
      },
    },
    {
      id: 90,
      name: 'Nico Hischier',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 79, toiPerGame: 1185 },
        scoring: {
          goals: 28,
          assists: 44,
          plusMinus: 6,
          pim: 40,
          ppg: 9,
          ppa: 14,
          shg: 2,
          sha: 1,
          gwg: 4,
          sog: 196,
          shPct: 14.3,
          fw: 623,
          fl: 478,
          hits: 54,
          blocks: 46,
        },
      },
    },
    {
      id: 91,
      name: 'Nino Niederreiter',
      positions: new Set(['RW']),
      stats: {
        utility: { gp: 77, toiPerGame: 1080 },
        scoring: {
          goals: 26,
          assists: 30,
          plusMinus: 2,
          pim: 44,
          ppg: 7,
          ppa: 9,
          shg: 1,
          sha: 0,
          gwg: 4,
          sog: 174,
          shPct: 14.9,
          fw: 89,
          fl: 78,
          hits: 89,
          blocks: 34,
        },
      },
    },
    {
      id: 92,
      name: 'Michael Bunting',
      positions: new Set(['LW']),
      stats: {
        utility: { gp: 79, toiPerGame: 1080 },
        scoring: {
          goals: 24,
          assists: 38,
          plusMinus: 8,
          pim: 56,
          ppg: 7,
          ppa: 12,
          shg: 1,
          sha: 0,
          gwg: 3,
          sog: 167,
          shPct: 14.4,
          fw: 112,
          fl: 89,
          hits: 98,
          blocks: 28,
        },
      },
    },
    {
      id: 93,
      name: 'Drake Batherson',
      positions: new Set(['RW', 'C']),
      stats: {
        utility: { gp: 74, toiPerGame: 1110 },
        scoring: {
          goals: 28,
          assists: 38,
          plusMinus: 4,
          pim: 22,
          ppg: 9,
          ppa: 13,
          shg: 0,
          sha: 0,
          gwg: 4,
          sog: 184,
          shPct: 15.2,
          fw: 156,
          fl: 123,
          hits: 38,
          blocks: 26,
        },
      },
    },
    {
      id: 94,
      name: 'Pierre-Luc Dubois',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 81, toiPerGame: 1200 },
        scoring: {
          goals: 27,
          assists: 43,
          plusMinus: 5,
          pim: 46,
          ppg: 8,
          ppa: 14,
          shg: 1,
          sha: 0,
          gwg: 4,
          sog: 196,
          shPct: 13.8,
          fw: 556,
          fl: 423,
          hits: 72,
          blocks: 48,
        },
      },
    },
    {
      id: 95,
      name: 'Josh Anderson',
      positions: new Set(['RW']),
      stats: {
        utility: { gp: 76, toiPerGame: 1080 },
        scoring: {
          goals: 26,
          assists: 28,
          plusMinus: 1,
          pim: 62,
          ppg: 7,
          ppa: 8,
          shg: 0,
          sha: 0,
          gwg: 4,
          sog: 178,
          shPct: 14.6,
          fw: 89,
          fl: 78,
          hits: 134,
          blocks: 29,
        },
      },
    },
    {
      id: 96,
      name: 'Jack Quinn',
      positions: new Set(['RW']),
      stats: {
        utility: { gp: 70, toiPerGame: 1080 },
        scoring: {
          goals: 24,
          assists: 34,
          plusMinus: 2,
          pim: 18,
          ppg: 8,
          ppa: 12,
          shg: 0,
          sha: 0,
          gwg: 3,
          sog: 162,
          shPct: 14.8,
          fw: 89,
          fl: 67,
          hits: 28,
          blocks: 19,
        },
      },
    },
    {
      id: 97,
      name: 'Dawson Mercer',
      positions: new Set(['C', 'RW']),
      stats: {
        utility: { gp: 80, toiPerGame: 1095 },
        scoring: {
          goals: 26,
          assists: 36,
          plusMinus: 4,
          pim: 28,
          ppg: 7,
          ppa: 11,
          shg: 1,
          sha: 0,
          gwg: 4,
          sog: 178,
          shPct: 14.6,
          fw: 345,
          fl: 267,
          hits: 52,
          blocks: 34,
        },
      },
    },
    {
      id: 98,
      name: 'Tanner Jeannot',
      positions: new Set(['LW']),
      stats: {
        utility: { gp: 73, toiPerGame: 1050 },
        scoring: {
          goals: 24,
          assists: 22,
          plusMinus: -1,
          pim: 82,
          ppg: 5,
          ppa: 5,
          shg: 0,
          sha: 0,
          gwg: 3,
          sog: 156,
          shPct: 15.4,
          fw: 89,
          fl: 78,
          hits: 178,
          blocks: 28,
        },
      },
    },
    {
      id: 99,
      name: 'Rickard Henriksson',
      positions: new Set(['C']),
      stats: {
        utility: { gp: 75, toiPerGame: 1095 },
        scoring: {
          goals: 22,
          assists: 34,
          plusMinus: 2,
          pim: 34,
          ppg: 6,
          ppa: 11,
          shg: 1,
          sha: 0,
          gwg: 3,
          sog: 167,
          shPct: 13.2,
          fw: 423,
          fl: 323,
          hits: 48,
          blocks: 36,
        },
      },
    },
    {
      id: 100,
      name: 'Cole Perfetti',
      positions: new Set(['C', 'LW']),
      stats: {
        utility: { gp: 72, toiPerGame: 1080 },
        scoring: {
          goals: 20,
          assists: 36,
          plusMinus: 1,
          pim: 22,
          ppg: 6,
          ppa: 13,
          shg: 0,
          sha: 0,
          gwg: 2,
          sog: 156,
          shPct: 12.8,
          fw: 312,
          fl: 245,
          hits: 34,
          blocks: 24,
        },
      },
    },
  ];

  getPlayers(): Observable<Player[]> {
    return of(this.mockPlayers);
  }
}
